[2022-05-22 03:02:49,663] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.transform_n_load_dataframe manual__2022-05-22T02:35:48.168632+00:00 [queued]>
[2022-05-22 03:02:49,677] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.transform_n_load_dataframe manual__2022-05-22T02:35:48.168632+00:00 [queued]>
[2022-05-22 03:02:49,677] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 03:02:49,677] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-22 03:02:49,677] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 03:02:49,695] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transform_n_load_dataframe> on 2022-05-22 02:35:48.168632+00:00
[2022-05-22 03:02:49,701] {standard_task_runner.py:52} INFO - Started process 878 to run task
[2022-05-22 03:02:49,705] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Teste_ETL_Raízen', 'transform_n_load_dataframe', 'manual__2022-05-22T02:35:48.168632+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmp_h7l_r_n', '--error-file', '/tmp/tmpn3h4s3t_']
[2022-05-22 03:02:49,706] {standard_task_runner.py:80} INFO - Job 47: Subtask transform_n_load_dataframe
[2022-05-22 03:02:49,772] {task_command.py:369} INFO - Running <TaskInstance: Teste_ETL_Raízen.transform_n_load_dataframe manual__2022-05-22T02:35:48.168632+00:00 [running]> on host de43a65d8e31
[2022-05-22 03:02:49,863] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Teste_ETL_Raízen
AIRFLOW_CTX_TASK_ID=transform_n_load_dataframe
AIRFLOW_CTX_EXECUTION_DATE=2022-05-22T02:35:48.168632+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-22T02:35:48.168632+00:00
[2022-05-22 03:02:52,193] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_Raizen.py", line 112, in transform_n_load_datas
    df.to_parquet(persist_path, engine='fastparquet', partition_cols=['product', 'year_month'])
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 2685, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 412, in to_parquet
    impl = get_engine(engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 66, in get_engine
    return FastParquetImpl()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 255, in __init__
    "fastparquet", extra="fastparquet is required for parquet support."
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
[2022-05-22 03:02:52,203] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Teste_ETL_Raízen, task_id=transform_n_load_dataframe, execution_date=20220522T023548, start_date=20220522T030249, end_date=20220522T030252
[2022-05-22 03:02:52,214] {standard_task_runner.py:97} ERROR - Failed to execute job 47 for task transform_n_load_dataframe (Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.; 878)
[2022-05-22 03:02:52,243] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-22 03:02:52,271] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
