[2022-05-19 03:30:09,571] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.nvalido scheduled__2022-05-19T02:30:00+00:00 [queued]>
[2022-05-19 03:30:09,595] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.nvalido scheduled__2022-05-19T02:30:00+00:00 [queued]>
[2022-05-19 03:30:09,596] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 03:30:09,596] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-19 03:30:09,598] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 03:30:09,625] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): nvalido> on 2022-05-19 02:30:00+00:00
[2022-05-19 03:30:09,632] {standard_task_runner.py:52} INFO - Started process 3648 to run task
[2022-05-19 03:30:09,637] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Teste_ETL_Raízen', 'nvalido', 'scheduled__2022-05-19T02:30:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpk7c7gnu8', '--error-file', '/tmp/tmpjqfq6oqp']
[2022-05-19 03:30:09,639] {standard_task_runner.py:80} INFO - Job 13: Subtask nvalido
[2022-05-19 03:30:09,746] {task_command.py:369} INFO - Running <TaskInstance: Teste_ETL_Raízen.nvalido scheduled__2022-05-19T02:30:00+00:00 [running]> on host c8caf9da75ac
[2022-05-19 03:30:09,909] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Teste_ETL_Raízen
AIRFLOW_CTX_TASK_ID=nvalido
AIRFLOW_CTX_EXECUTION_DATE=2022-05-19T02:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-19T02:30:00+00:00
[2022-05-19 03:30:09,912] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-19 03:30:09,915] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'Quantidade nao Ok'"]
[2022-05-19 03:30:09,942] {subprocess.py:85} INFO - Output:
[2022-05-19 03:30:09,953] {subprocess.py:92} INFO - Quantidade nao Ok
[2022-05-19 03:30:09,954] {subprocess.py:96} INFO - Command exited with return code 0
[2022-05-19 03:30:10,007] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Teste_ETL_Raízen, task_id=nvalido, execution_date=20220519T023000, start_date=20220519T033009, end_date=20220519T033010
[2022-05-19 03:30:10,060] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-19 03:30:10,136] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
