[2022-05-22 03:18:27,047] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx manual__2022-05-22T02:35:48.168632+00:00 [queued]>
[2022-05-22 03:18:27,055] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx manual__2022-05-22T02:35:48.168632+00:00 [queued]>
[2022-05-22 03:18:27,055] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 03:18:27,055] {taskinstance.py:1357} INFO - Starting attempt 3 of 3
[2022-05-22 03:18:27,055] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 03:18:27,067] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_in_xlsx> on 2022-05-22 02:35:48.168632+00:00
[2022-05-22 03:18:27,071] {standard_task_runner.py:52} INFO - Started process 107 to run task
[2022-05-22 03:18:27,073] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Teste_ETL_Raízen', 'convert_xls_in_xlsx', 'manual__2022-05-22T02:35:48.168632+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmp15b1ygbb', '--error-file', '/tmp/tmp1s2z48wu']
[2022-05-22 03:18:27,074] {standard_task_runner.py:80} INFO - Job 59: Subtask convert_xls_in_xlsx
[2022-05-22 03:18:27,116] {task_command.py:369} INFO - Running <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx manual__2022-05-22T02:35:48.168632+00:00 [running]> on host e2daa2993bb4
[2022-05-22 03:18:27,176] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Teste_ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_in_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-05-22T02:35:48.168632+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-22T02:35:48.168632+00:00
[2022-05-22 03:18:29,703] {python.py:173} INFO - Done. Returned value was: None
[2022-05-22 03:18:29,715] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Teste_ETL_Raízen, task_id=convert_xls_in_xlsx, execution_date=20220522T023548, start_date=20220522T031827, end_date=20220522T031829
[2022-05-22 03:18:29,734] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-22 03:18:29,770] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
